[tool.black]
line-length = 88
target-version = ["py310"]
exclude = ["venv", ".venv", "build", "dist", "notebooks"]

[tool.flake8]
max-line-length = 88
extend-ignore = ["E203", "W503"]
exclude = ["venv", ".venv", "build", "dist", "notebooks", "mlruns"]
